/** GLOBAL CONFIG */
export const GET_CONFIG_FAILED = 'GET_CONFIG_FAILED';
export const GET_CONFIG_SUCCESS = 'GET_CONFIG_SUCCESS';

/** APP PARAMS (Push Notifications) */
export const POST_APP_PARAMS_FAILED = 'POST_APP_PARAMS_FAILED';
export const POST_APP_PARAMS_SUCCESS = 'POST_APP_PARAMS_SUCCESS';
export const PUT_APP_PARAMS_LOGOUT_FAILED = 'PUT_APP_PARAMS_LOGOUT_FAILED';
export const PUT_APP_PARAMS_LOGOUT_SUCCESS = 'PUT_APP_PARAMS_LOGOUT_SUCCESS';

/** UPDATE STATE */
export const SET_APP_PARAMS = 'SET_APP_PARAMS';
