platform :ios, '10.0'
#source 'https://github.com/CocoaPods/Specs.git'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

def libs
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'RNLanguages', :path => '../node_modules/react-native-languages'
end

target 'RecetasAbuelaDev' do
  libs

  # target 'RecetasAbuelaTestsDev' do
  #   inherit! :complete
  #   # Pods for testing
  # end
end

target 'RecetasAbuelaPro' do
  libs

  # target 'RecetasAbuelaTestsPro' do
  #   inherit! :complete
  #   # Pods for testing
  # end
end

# Enables Flipper.
#
# Note that if you have use_frameworks! enabled, Flipper will not work and
# you should disable these next few lines.
use_flipper!
post_install do |installer|
  flipper_post_install(installer)
end
